Repository kelvinmburu/localshop, pull requests merged in 2022-07, with the labels that each got.

#5 add readme
  README.md
Labels: documentation

#8 docs: updated readme
  README.md
Labels: documentation

#9 docs: updated readme
  README.md
Labels: documentation

#10 Ft prod
  README.md
  backend/.gitignore
  front-end/localshop/angular.json
Labels: documentation

#12 Ft prod
  front-end/localshop/angular.json
  front-end/localshop/package-lock.json
  front-end/localshop/package.json
  front-end/localshop/src/app/app.component.html
  front-end/localshop/src/app/components/products/products.component.css
  front-end/localshop/src/app/components/products/products.component.html
  front-end/localshop/tsconfig.json
Labels: Critical

#14 Ft landingpage
  front-end/localshop/package-lock.json
  front-end/localshop/src/app/app.component.html
  front-end/localshop/src/app/components/footer/footer.component.html
  front-end/localshop/src/app/components/landingpage/landingpage.component.css
  front-end/localshop/src/app/components/landingpage/landingpage.component.html
  front-end/localshop/src/app/components/navbar/navbar.component.css
  front-end/localshop/src/app/components/navbar/navbar.component.html
  front-end/localshop/src/assets/Baloon.jpg
  front-end/localshop/src/assets/prdev.jpg
Labels: enhancement

#16 Feat: Create stores page
  front-end/localshop/src/app/app.component.html
  front-end/localshop/src/app/app.module.ts
  front-end/localshop/src/app/components/landingpage/landingpage.component.html
  front-end/localshop/src/app/components/stores/stores.component.css
  front-end/localshop/src/app/components/stores/stores.component.html
  front-end/localshop/src/app/components/stores/stores.component.ts
Labels: chore

#18 Ft clerk
  front-end/localshop/angular.json
  front-end/localshop/package-lock.json
  front-end/localshop/package.json
  front-end/localshop/src/app/app.component.html
  front-end/localshop/src/app/app.module.ts
  front-end/localshop/src/app/components/clerk/clerk.component.css
  front-end/localshop/src/app/components/clerk/clerk.component.html
  front-end/localshop/src/app/components/clerk/clerk.component.spec.ts
  front-end/localshop/src/app/components/clerk/clerk.component.ts
  front-end/localshop/src/app/components/products/products.component.css
  front-end/localshop/src/app/components/products/products.component.html
  front-end/localshop/src/app/components/products/products.component.ts
  front-end/localshop/src/app/components/request/request.component.css
  front-end/localshop/src/app/components/request/request.component.html
  front-end/localshop/src/app/components/request/request.component.spec.ts
  front-end/localshop/src/app/components/request/request.component.ts
  front-end/localshop/src/styles.css
Labels: chore

#20 chore: updated path in main html
  backend/localproje/settings.py
  front-end/localshop/src/app/app.component.html
Labels: chore

#21 Fix: Fix clerks page
  front-end/localshop/src/app/app-routing.module.ts
  front-end/localshop/src/app/app.module.ts
  front-end/localshop/src/app/components/add-user/add-user.component.html
  front-end/localshop/src/app/components/clerk/clerk.component.html
  front-end/localshop/src/app/components/products/products.component.html
Labels: chore

#23 Feat: Add new clerks
  front-end/localshop/src/app/components/add-user/add-user.component.html
  front-end/localshop/src/app/components/clerk/clerk.component.html
  front-end/localshop/src/app/components/clerk/clerk.component.ts
  front-end/localshop/src/app/services/shared.service.ts
Labels: build

#24 build & st: updated form with reset button|styled components
  front-end/localshop/src/app/components/add-user/add-user.component.css
  front-end/localshop/src/app/components/add-user/add-user.component.html
  front-end/localshop/src/app/components/add-user/add-user.component.ts
  front-end/localshop/src/app/components/clerk/clerk.component.css
  front-end/localshop/src/app/components/clerk/clerk.component.html
  front-end/localshop/src/app/components/clerk/clerk.component.ts
Labels: feature

#25 Ft prod
  backend/localapp/models.py
  front-end/localshop/src/app/components/products/products.component.html
  front-end/localshop/src/app/components/products/products.component.ts
  front-end/localshop/src/app/services/shared.service.ts
  front-end/localshop/tsconfig.json
Labels: chore

#26 Development
  README.md
  backend/localapp/models.py
  front-end/localshop/src/app/components/defective-goods/defective-goods.component.html
  front-end/localshop/src/app/components/defective-goods/defective-goods.component.ts
  front-end/localshop/src/app/components/defective-goods/defective.ts
  front-end/localshop/src/app/components/footer/footer.component.html
  front-end/localshop/src/app/components/orders/orders.component.html
  front-end/localshop/src/app/components/products/products.component.html
  front-end/localshop/src/app/services/shared.service.ts
Labels: enhancement, Critical

#27 add hamburger to navbar
  front-end/localshop/src/app/components/navbar/navbar.component.html
Labels: enhancement

#28 fx: fixed sidebar
  front-end/localshop/src/app/components/products/products.component.html
  front-end/localshop/src/app/components/products/products.component.ts
  front-end/localshop/src/styles.css
Labels: chore

#29 add request page
  front-end/localshop/src/app/app-routing.module.ts
  front-end/localshop/src/app/app.module.ts
  front-end/localshop/src/app/components/dashboard/dashboard.component.html
  front-end/localshop/src/assets/dashboard_icons/checklist.png
Labels: enhancement

#30 Development
  backend/localapp/models.py
  front-end/localshop/src/app/components/defective-goods/defective-goods.component.html
  front-end/localshop/src/app/components/defective-goods/defective-goods.component.ts
  front-end/localshop/src/app/components/products/products.component.html
  front-end/localshop/src/app/components/products/products.component.ts
  front-end/localshop/src/app/services/shared.service.ts
Labels: feature

#37 Development
  front-end/localshop/src/app/components/add-user/add-user.component.css
  front-end/localshop/src/app/components/clerk/clerk.component.css
  front-end/localshop/src/app/components/contact/contact.component.css
  front-end/localshop/src/app/components/dashboard/dashboard.component.css
  front-end/localshop/src/app/components/dashboard/dashboard.component.html
  front-end/localshop/src/app/components/defective-goods/defective-goods.component.ts
  front-end/localshop/src/app/components/footer/footer.component.html
  front-end/localshop/src/app/components/landingpage/landingpage.component.css
  front-end/localshop/src/app/components/landingpage/landingpage.component.html
  front-end/localshop/src/app/components/login/login.component.css
  front-end/localshop/src/app/components/navbar/navbar.component.css
  front-end/localshop/src/app/components/products/products.component.css
  front-end/localshop/src/app/components/report/report.component.css
  front-end/localshop/src/app/components/report/report.component.html
  front-end/localshop/src/app/components/report/report.component.ts
  front-end/localshop/src/assets/graph1.jpg
Labels: enhancement

#38 Development
  front-end/localshop/src/app/components/about/about.component.css
  front-end/localshop/src/app/components/about/about.component.html
  front-end/localshop/src/app/components/landingpage/landingpage.component.html
  front-end/localshop/src/app/services/shared.service.ts
  front-end/localshop/src/assets/inventory.jpg
Labels: enhancement

#43 Ft prod
  front-end/localshop/angular.json
  front-end/localshop/package-lock.json
  front-end/localshop/package.json
  front-end/localshop/src/app/app-routing.module.ts
  front-end/localshop/src/app/app.module.ts
  front-end/localshop/src/app/components/login/login.component.css
  front-end/localshop/src/app/components/login/login.component.html
  front-end/localshop/src/app/components/register/register.component.css
  front-end/localshop/src/app/components/register/register.component.html
  front-end/localshop/src/app/components/register/register.component.spec.ts
  front-end/localshop/src/app/components/register/register.component.ts
  front-end/localshop/src/app/interface/user.ts
  front-end/localshop/src/app/services/shared.service.ts
  front-end/localshop/src/app/user.ts
  front-end/localshop/src/index.html
  front-end/localshop/src/styles.css
Labels: enhancement, build
